name: 'Setup Git for Windows SDK'
description: 'Set up an environment to develop Git for Windows'
author: 'Johannes Schindelin'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
